version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "shanumuru"
github_repo = "sampipe"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws-us-gov:iam::146825952482:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-riUlP192rSjJ"
cloudformation_execution_role = "arn:aws-us-gov:iam::146825952482:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-fS9jdC6MUUSv"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-evivns4ysyjz"
image_repository = ""
region = "us-gov-east-1"

[stgqa.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws-us-gov:iam::146825952482:role/aws-sam-cli-managed-stgqa-pip-PipelineExecutionRole-d7TyC45JTYIt"
cloudformation_execution_role = "arn:aws-us-gov:iam::146825952482:role/aws-sam-cli-managed-stgqa-CloudFormationExecutionRo-ROLlrlQQoujS"
artifacts_bucket = "aws-sam-cli-managed-stgqa-pipeline-artifactsbucket-p3cdrgyddjov"
image_repository = ""
region = "us-gov-east-1"
